### ISSUE TITLE
app.run(host='0.0.0.0')

### ISSUE THREAD

**Issue by BIG-Ani** [embbnux/RpiCloudManager#1]
通过浏览器对树莓派进行访问和设置http://your_raspberry_ip:2000
为什么我实践没有正常通信？（树莓派通过网线直接与PC相连，PC-ip:192.168.137.1，树莓派-ip:192.168.137.222）
PC浏览器：192.168.137.222；然后报错404

**Comment by embbnux** [comment]
http://192.168.137.222:2000
